FROM fuco1/build-base:hirsute-1.0

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    libboost-all-dev \
    libqt5x11extras5-dev \
    qt5-qmake \
    && rm -rf /var/lib/apt/lists/*

COPY ./docker-build.sh /docker-build.sh

ENTRYPOINT ["/bin/bash"]
CMD ["/docker-build.sh"]
