#!/bin/bash

docker run --rm --privileged \
       --name twmnd \
       --env DBUS_SESSION_BUS_ADDRESS="$DBUS_SESSION_BUS_ADDRESS" \
       --env DISPLAY="unix$DISPLAY" \
       -v /run/user/1000/bus:/run/user/1000/bus \
       -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket \
       -v /tmp/.X11-unix:/tmp/.X11-unix \
       -v "$XDG_CONFIG_HOME/twmn/twmn.conf:/.config/twmn/twmn.conf" \
       --security-opt apparmor=unconfined \
       -u 1000:1000 \
       "fuco1/twmnd:latest"
